package me.dcdev.demobasescopebean;


import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("prototype")
public class ReportGenerationTask {
    private final String taskId;

    public ReportGenerationTask() {
        // Gera um identificador único simples para cada tarefa
        this.taskId = "Task-" + System.nanoTime();
    }

    public String generateReport() {
        // Aqui seria colocado a lógica real de geração de relatório
        return "Report generated by " + taskId;
    }
}
